import React, { useState } from "react"
import { 
    WiMoonAltFull, 
    WiMoonAltWaxingCrescent1, 
    WiMoonAltWaxingCrescent4, 
    WiMoonAltWaxingGibbous1, 
    WiMoonAltWaxingGibbous4, 
    WiMoonAltNew } from 'react-icons/wi'

export default function Accordion() {
    const services = [
        {
            id: 'branding',
            Icon: WiMoonAltNew,
            title: 'Branding',
            content: 'From logo design to fonts & colors, we can help you find your company’s voice. Establishing a brand and sticking to it is extremely important when it comes to capturing and holding the attention of potential clients.'
        },
        {
            id: 'strategy',
            Icon: WiMoonAltWaxingCrescent1,
            title: 'Strategy',
            content: 'Figuring out your goals. Short term and long term. Using data generated by your ads and/or website analytics, we figure out what’s working and use it to plan your best course of action, always keeping inline with your branding.'
        },
        {
            id: 'development',
            Icon: WiMoonAltWaxingCrescent4,
            title: 'Development',
            content: 'Once we have your brand carved out & a strategy or plan of action, it’s time to build your dream. We offer website creation, graphic design, photography, and videography, and can support you in sourcing all of your digital assets.'
        },
        {
            id: 'advertising',
            Icon: WiMoonAltWaxingGibbous1,
            title: 'Advertising',
            content: 'Using mediums including Google Ads, YouTube, Facebook, and Instagram, we build customized targeting; growing your organic reach and developing vast re-marketing audiences.'
        },
        {
            id: 'analytics',
            Icon: WiMoonAltWaxingGibbous4,
            title: 'Analytics',
            content: 'We send out detailed monthly reports summarizing where and how all advertising dollars are spent. This data will also be analyzed and used to create new strategies for the future.'
        },
        {
            id: 'socials',
            Icon: WiMoonAltFull,
            title: 'Socials',
            content: 'Managing social media can be a time consuming task. Our team can help take that off of your hands, freeing up your psychological CPU to focus on managing your business.'
        },
    ]

    const [activeItem, setActiveItem] = useState(false)

    const handleActive = (item) => {
        console.log(item, 'hi')
        setActiveItem(item)
    }

    return (
    <div className="flex justify-center mt-10">
        <div className="flex gap-2 p-2 bg-white/20">
            { services.map(s => {
                return (
                    <Collapsible 
                        key={s.id}
                        id={s.id} 
                        Icon={s.Icon}
                        title={s.title}
                        content={s.content} 
                        isActive={s.id === activeItem}
                        handleActive={handleActive}
                    />)
                })
            }
        </div>
    </div>
    )
}

export function Collapsible({ id, title, content, Icon, isActive, handleActive }) {
    
    return (
        <div onClick={() => handleActive(id)} className={`${isActive ? `max-w-[350px]` : `w-20`} transition-width transition-1000 ease group bg-black/80 hover:bg-black overflow-hidden h-62 md:h-96 flex cursor-pointer`}>
            <h3 className={`${isActive ? `hidden` : ``} group text-base md:text-xl font-SpaceAge m-0 w-full self-start text-left rotate-90 relative top-2`} 
                id={id}
            >
                <button
                    className={`${!isActive ? `text-blx-blue` : `text-blx-gold`} w-full relative flex justify-between items-center py-4 px-5 text-left`}
                    type="button"
                >
                    {title}
                </button>
                <Icon className='h-[35px] w-[35px] absolute top-5 left-[325px] rotate-90 group-hover:text-blx-gold' />
            </h3>
            
            <div className={`${isActive ? `w-fit` : `w-0`} text-left font-regular text-base py-6 px-6 h-full transition-width transition-slowest ease flex flex-col justify-center gap-4`}>
                <p className="font-SpaceAge text-xl text-blx-gold">
                    {title}
                </p>
                <p className="font-thin !font-sans">{content}</p>
            </div>
        </div>
    )
}